image: maven:3.3.3-jdk-8
stages:
  - build
  - test
  - deploy
build_job:
  stage: build
  only:
    - master
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true
build_merge_job:
  stage: build
  except:
    - master
    - tags
  script:
    - git merge origin master
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true
test_sonar_preview_job:
  stage: test
  except:
    - master
    - tags
  script:
    - git merge origin master
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview
test_sonar_job:
  stage: test
  only:
    - master
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.jdbc.url=$SONAR_DB -Dsonar.jdbc.username=$SONAR_USERNAME -Dsonar.jdbc.password=$SONAR_PASSWORD
deploy_job:
  stage: deploy
  only:
    - master
  script:
    - mvn --batch-mode deploy -Dmaven.test.skip=true -Djacoco.skip=true
deploy_tags_job:
  stage: deploy
  only:
    - tags
  script:
    - mvn --batch-mode org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=$CI_BUILD_REF_NAME -DgenerateBackupPoms=false
    - mvn --batch-mode deploy -Dmaven.test.skip=true -Djacoco.skip=true