image: maven:3.3.3-jdk-8
stages:
  - build
  - test
build_job:
  stage: build
  script:
    - mvn -q --batch-mode compile -Dmaven.test.skip=true
test_job:
  stage: test
  script:
    - mvn -q --batch-mode verify